# https://github.com/LibraryOfCongress/bagit-python/issues/70
{% set name = "bagit" %}
{% set version = "1.5.5" %}
{% set commit = "c0ba65714823c054b3a8b610e8967e70478204f3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/LibraryOfCongress/bagit-python/archive/{{ commit }}.tar.gz
  sha256: 86a60cc6d78cf3b57bd9df56122e8244424285c016a93794b0dd91cbcd0e9cf4

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
  run:
    - python
    - setuptools

test:
  imports:
    - bagit
  commands:
    - bagit.py --version

about:
  home: https://libraryofcongress.github.io/bagit-python/
  summary: 'Work with BagIt packages from Python'
  license: Public-Domain
  license_family: Public-Domain
  dev_url: https://github.com/LibraryOfCongress/bagit-python
  doc_url: https://libraryofcongress.github.io/bagit-python/

extra:
  recipe-maintainers:
    - kwilcox
